"""empty message

Revision ID: 211e6b5db14c
Revises: 
Create Date: 2020-04-26 11:56:47.360783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211e6b5db14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.alter_column('hall', 'is_vip',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'actors',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('movies', 'blurb',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('movies', 'certificate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('movies', 'picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('movies', 'poster',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('order_detail', 'pay_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('order_detail', 'seat_column',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_detail', 'seat_row',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_detail', 'ticket_uuid',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('order_detail', 'unique_identity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('schedule', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('schedule', 'end_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('schedule', 'price',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('schedule', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('schedule', 'price',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('schedule', 'end_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('schedule', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order_detail', 'unique_identity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('order_detail', 'ticket_uuid',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('order_detail', 'seat_row',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'seat_column',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'pay_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('movies', 'poster',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('movies', 'picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('movies', 'certificate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('movies', 'blurb',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('movies', 'actors',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('hall', 'is_vip',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
